apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: webapp
spec:
  containers:
   - name: mysql
     image: mysql:5
     env:
      - name: MYSQL_ROOT_PASSWORD
        value: $PASSWD
      - name: MYSQL_DATABASE
        value: fleetman

---
kind: Service
apiVersion: v1
metadata: 
  name: database
spec:
  selector:
    app: webapp
  ports:
  - port: 3306
  type: ClusterIP
